version: '3.8'

services:

  rest-api:
    image: rest-api-image
    build:
      context: ./rest-api
      dockerfile: Dockerfile
    ports:
      - "8081:8080" # Map ASP.NET default port 8080 (=container) to 8081 (=host)
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080 # Stellt sicher, dass nur HTTP verwendet wird

  web-ui:
    image: web-ui-image
    build:
        context: ./web-ui
        dockerfile: Dockerfile
    ports:
        - "80:80"
    volumes:
        - ./web-ui/nginx.conf:/etc/nginx/nginx.conf  # Binde die Nginx-Konfigurationsdatei ein
        - ./web-ui/wwwroot:/app/wwwroot  # Statische Dateien mounten
    depends_on:
        - rest-api
