version: '3.8'

services:
  dms-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8080" # Map ASP.NET default port 8080 to 8081
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
