version: '3.8'

services:

  dms:
    image: rest-api-image
    build:
      context: ./RestAPI
      dockerfile: Dockerfile
    ports:
      - "8080:8080" # Map ASP.NET default port 8080 to 8080
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080 # Stellt sicher, dass nur HTTP verwendet wird

  web-ui:
    image: web-ui-image
    build:
        context: ./web-ui
        dockerfile: Dockerfile
    ports:
        - "80:80"
    volumes:
        - ./web-ui/nginx.conf:/etc/nginx/nginx.conf  # Binde die Nginx-Konfigurationsdatei ein
        - ./web-ui/wwwroot:/app/wwwroot  # Statische Dateien mounten
    depends_on:
        - dms
